### ISSUE TITLE
Date of release or roadmap ?

### ISSUE THREAD

**Issue by By-oussef** [rodolfoberrios/chevereto-core#1]
Hello, mr the developer I am interested in your core I put a star. I read in the description that I can use it in production.

Can you set up a road map to see what's left? Or give a date. Because we are interestering with that.

Thank you.

**Comment by rodolfoberrios** [comment]
I'm sorry but it seems that you got it wrong. From the README:

`This project is in alpha status and its usage under production is highly discouraged.`

At this time, this framework is still a work in progress.

The public availability of this framework is still not certain and it must be shaped by Chevereto (image hosting app).
